config/routes.rb
Rails.application.routes.draw do
  get "wiki_posts/example"
  resources :wiki_posts
  get 'welcome/index'
  get 'welcome/about'
  get "/about", to: redirect("/welcome/about")
  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wiki_post.rb
class WikiPost < ApplicationRecord
  has_one_attached :image

  def meta
    "Created by " + self.author + " on " + I18n.l(self.created_at, format: long) + " and last updated " + I18n.l(self.updated_at, format: long)
    # "Created by " + self.author + " on " + self.created_at.to_s+ " and last updated " + self.updated_at.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @wiki_posts = WikiPost.all
  end

  def about

  end
end

app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ show edit update destroy ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
  end

  def example
    render "example"
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wiki_post
    @wiki_post = WikiPost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def wiki_post_params
    params.fetch(:wiki_post, {}).permit(:title, :description, :image, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWiki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Wiki Information</h1>

app/views/welcome/index.html.erb
<h1>Wiki</h1>

<%= render "wiki_posts/list", wiki_posts: @wiki_posts %>


<%= link_to "About", welcome_about_path %>
<%= link_to "New post", new_wiki_post_path %>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title, "Post title" %>
  <%= form.text_field :title %>

  <%= form.label :image, "Post image" %>
  <%= form.file_field :image %>

  <%= form.label :title, "Post description" %>
  <%= form.text_field :description %>

  <%= form.label :title, "What's your name?" %>
  <%= form.text_field :author %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_list.html.erb
<div class="posts">
  <% @wiki_posts.each do |wiki_post| %>
    <h4><%= wiki_post.title %></h4>
    <p>
      <%= link_to "Show this wiki post", wiki_post_path(wiki_post), class: "wikiLink" %>
      <%= image_tag wiki_post.image, class: "thumbnail" %>
    </p>
  <% end %>
</div>

app/views/wiki_posts/_meta.html.erb
<div class="meta">
  Created by &nbsp;<strong><%= @wiki_post.author %></strong>
  on &nbsp;<strong><%= @wiki_post.created_at %>&nbsp;</strong> and last updated
  &nbsp;<strong><%= @wiki_post.updated_at %></strong>
</div>

app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  <%= link_to "Show this wiki post", @wiki_post %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/example.html.erb
<h1>Wiki Page Title</h1>

<p>Wiki Page Body</p>

<div>
  <span>Wiki Page Author</span>
  <span>Wiki Page Creation Date</span>
</div>

<div>
  <%= link_to "Home", wiki_posts_path %>
  <%= link_to "New Wiki Post", new_wiki_post_path %>
</div>

app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wiki posts</h1>

<%= render "list", wiki_posts: @wiki_posts %>

<%= link_to "New wiki post", new_wiki_post_path %>

app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @wiki_post.title %></h1>
<p>
  <%= image_tag @wiki_post.image %>
</p><p>
  <%= @wiki_post.description %>
</p>

<%= render "meta", wiki_post: @wiki_post %>


<div>
  <%= link_to "Edit this wiki post", edit_wiki_post_path(@wiki_post) %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>

  <%= button_to "Destroy this wiki post", @wiki_post, method: :delete %>
</div>